# This File is Automaticly Generated. Changes inside of this won't persist. For more Information Look into /home/snoweuph/Workspace/rice/rice-bowl
colors:
  primary:
    background: '#2e3440'
    foreground: '#ced4de'
  normal:
    white: '#ced4de'
    black: '#2e3440'
    red: '#bf616a'
    yellow: '#d08770'
    green: '#80bf83'
    cyan: '#7ebdbc'
    blue: '#5e81ac'
    magenta: '#937db5'
  bright:
    white: '#e5e9f0'
    black: '#434c5e'
    yellow: '#ebcb8b'
    green: '#adbf7c'
    blue: '#7db0d1'
    magenta: '#b5779c'


