# This File is Automaticly Generated. Changes inside of this won't persist. For more Information Look into /home/snoweuph/Workspace/rice/rice-bowl
window:
  padding:
    x: 4
    y: 4
  opacity: 0.8

