#!/bin/bash

RICE_FONT_NORMAL="Hack Nerd Font"
RICE_FONT_MONO="Hack Nerd Font Mono"
RICE_FONT_ICONS="Hack Nerd Font Mono"

RICE_FONT_SIZE_SMALL=12
RICE_FONT_SIZE_NORMAL=16
RICE_FONT_SIZE_BIG=20

RICE_FONT_SIZE_ICONS_NORMAL=28
RICE_FONT_SIZE_ICONS_BIG=64
