#!/bin/bash

RICE_DIR_CONFIG=~/.config
RICE_DIR_RICE_BOWL=$RICE_DIR_CONFIG/rice-bowl
RICE_DIR_AUTORUN=~/.autorun
RICE_DIR_FONTS=/usr/share/fonts
RICE_DIR_IMAGES=~/Bilder
RICE_DIR_WALLPAPER=$RICE_DIR_IMAGES/Wallpaper
RICE_DIR_SCREENSHOTS=$RICE_DIR_IMAGES/Screenshots
