#!/bin/bash

RICE_THEME=nord

RICE_PADDING=4
RICE_GAPS=12

RICE_DPI=96
RICE_ELEMENT_HEIGHT_SMALL=26
RICE_ELEMENT_HEIGHT_MEDIUM=$(($((RICE_ELEMENT_HEIGHT_SMALL*9))/2))
RICE_ELEMENT_HEIGHT_BIG=$(($((RICE_ELEMENT_HEIGHT_MEDIUM*9))/2))

RICE_BORDER_RADIUS=12
RICE_BORDER_THICKNESS=4

RICE_OPACITY_FLOAT="0.8"
RICE_INACTIVE_OPACITY_FLOAT="1.0"
ROCE_OPACITY_PERCENTAGE="80%"
